"""Database bootstrap helpers for the Living Library project.

These helpers create the Postgres objects that the application and ingestion
scripts expect. The bootstrap is intentionally idempotent so it can run on a
fresh database or on an existing one without damaging data.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import text


SCHEMA_STATEMENTS: tuple[str, ...] = (
    "CREATE EXTENSION IF NOT EXISTS vector",
    """
    CREATE TABLE IF NOT EXISTS material (
        material_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        subtitle TEXT,
        edition TEXT,
        year INTEGER,
        type TEXT,
        tier INTEGER,
        status TEXT,
        is_global BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS author (
        author_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        author_name TEXT NOT NULL UNIQUE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS topic (
        topic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic_name TEXT NOT NULL UNIQUE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS file_asset (
        file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        material_id INTEGER NOT NULL REFERENCES material(material_id) ON DELETE CASCADE,
        storage_path TEXT NOT NULL,
        storage_provider TEXT NOT NULL DEFAULT 'local',
        storage_bucket TEXT,
        pages INTEGER,
        is_accessible BOOLEAN NOT NULL DEFAULT TRUE,
        is_primary BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT file_asset_supabase_bucket_required
            CHECK (storage_provider <> 'supabase' OR storage_bucket IS NOT NULL)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS material_author (
        material_id INTEGER NOT NULL REFERENCES material(material_id) ON DELETE CASCADE,
        author_id INTEGER NOT NULL REFERENCES author(author_id) ON DELETE CASCADE,
        PRIMARY KEY (material_id, author_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS material_topic (
        material_id INTEGER NOT NULL REFERENCES material(material_id) ON DELETE CASCADE,
        topic_id INTEGER NOT NULL REFERENCES topic(topic_id) ON DELETE CASCADE,
        PRIMARY KEY (material_id, topic_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS text_chunk (
        chunk_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_id INTEGER NOT NULL REFERENCES file_asset(file_id) ON DELETE CASCADE,
        page_number INTEGER NOT NULL,
        chunk_text TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT text_chunk_page_positive CHECK (page_number > 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS chunk_embedding (
        chunk_id INTEGER PRIMARY KEY REFERENCES text_chunk(chunk_id) ON DELETE CASCADE,
        embedding vector(384) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS duplicate_candidate (
        candidate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        material_id_1 INTEGER NOT NULL REFERENCES material(material_id) ON DELETE CASCADE,
        material_id_2 INTEGER NOT NULL REFERENCES material(material_id) ON DELETE CASCADE,
        similarity_score DOUBLE PRECISION NOT NULL,
        detection_method TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT duplicate_candidate_score_range CHECK (similarity_score >= 0 AND similarity_score <= 1),
        CONSTRAINT duplicate_candidate_distinct_materials CHECK (material_id_1 <> material_id_2)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_material_global_tier_status ON material (is_global, tier, status)",
    "CREATE INDEX IF NOT EXISTS idx_material_author_author_id ON material_author (author_id)",
    "CREATE INDEX IF NOT EXISTS idx_material_topic_topic_id ON material_topic (topic_id)",
    "CREATE INDEX IF NOT EXISTS idx_file_asset_material_id ON file_asset (material_id)",
    "CREATE INDEX IF NOT EXISTS idx_file_asset_primary_per_material ON file_asset (material_id) WHERE is_primary",
    "CREATE INDEX IF NOT EXISTS idx_text_chunk_file_page ON text_chunk (file_id, page_number)",
    "CREATE INDEX IF NOT EXISTS idx_duplicate_candidate_status_score ON duplicate_candidate (status, similarity_score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_chunk_embedding_vector ON chunk_embedding USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)",
    """
    CREATE OR REPLACE FUNCTION get_material_stats()
    RETURNS TABLE (
        total_materials BIGINT,
        total_authors BIGINT,
        total_topics BIGINT,
        total_chunks BIGINT,
        total_embeddings BIGINT,
        materials_by_tier JSONB
    )
    LANGUAGE sql
    STABLE
    AS $$
        SELECT
            (SELECT COUNT(*) FROM material WHERE is_global = TRUE) AS total_materials,
            (SELECT COUNT(*) FROM author) AS total_authors,
            (SELECT COUNT(*) FROM topic) AS total_topics,
            (SELECT COUNT(*) FROM text_chunk) AS total_chunks,
            (SELECT COUNT(*) FROM chunk_embedding) AS total_embeddings,
            COALESCE(
                (
                    SELECT jsonb_object_agg(tier_label, tier_count)
                    FROM (
                        SELECT
                            COALESCE(m.tier::TEXT, 'unclassified') AS tier_label,
                            COUNT(*) AS tier_count
                        FROM material m
                        WHERE m.is_global = TRUE
                        GROUP BY 1
                        ORDER BY 1
                    ) tier_counts
                ),
                '{}'::jsonb
            ) AS materials_by_tier;
    $$
    """,
)


async def ensure_schema_with_session(session: Any) -> None:
    """Create the database objects required by the app using SQLAlchemy."""

    for statement in SCHEMA_STATEMENTS:
        await session.execute(text(statement))


async def ensure_schema_with_connection(connection: Any) -> None:
    """Create the database objects required by the app using asyncpg."""

    for statement in SCHEMA_STATEMENTS:
        await connection.execute(statement)